const api = globalThis.browser?.storage ? globalThis.browser : globalThis.chrome;
const KEYS = { sessions: 'tabSessions', settings: 'saveTabsSettings', rules: 'autoSaveRules', backups: 'scheduledBackups' };
const ALARM = 'save-tabs-scheduled-backup';
const TEXT = { en: { settings: 'SETTINGS', preferences: 'Preferences', language: 'Language', theme: 'Theme', sync: 'Enable browser sync', shortcuts: 'Keyboard shortcuts', shortcutsCopy: 'Save the current window with Ctrl+Shift+S and open the library with Ctrl+Shift+L. You can customize them in your browser extension shortcuts.', customize: 'Customize shortcuts', backups: 'Scheduled backups', backupsCopy: 'Create a private backup in browser storage automatically. The latest 10 backups are retained.', enableBackups: 'Enable scheduled backups', frequency: 'Frequency', daily: 'Daily', weekly: 'Weekly', stats: 'Organization statistics', rules: 'Automatic saving rules', rulesCopy: 'Save tabs from matching domains into a chosen session.', addRule: 'Add rule', privacy: 'Privacy', privacyCopy: 'Save Tabs stores titles, URLs, tags, notes, rules, and preferences in browser storage. Sync is opt-in.', privacyLink: 'Read privacy policy', noRules: 'No rules yet.', enabled: 'Enabled', disabled: 'Disabled', edit: 'Edit', delete: 'Delete', deletedSession: 'Deleted session', editRule: 'Edit rule', domains: 'Domains', saveInto: 'Save into', cancel: 'Cancel', saveRule: 'Save rule', backupsOff: 'Scheduled backups are off.', backupStatus: '{count} saved backups · last: {date}', sessions: 'Sessions', tabs: 'Saved tabs', favorites: 'Favorites', tagged: 'Tagged tabs' }, es: { settings: 'CONFIGURACIÓN', preferences: 'Preferencias', language: 'Idioma', theme: 'Tema', sync: 'Activar sincronización del navegador', shortcuts: 'Atajos de teclado', shortcutsCopy: 'Guarda la ventana actual con Ctrl+Shift+S y abre la biblioteca con Ctrl+Shift+L. Puedes personalizarlos en los atajos de extensiones del navegador.', customize: 'Personalizar atajos', backups: 'Respaldos programados', backupsCopy: 'Crea un respaldo privado automáticamente en el almacenamiento del navegador. Se conservan los 10 más recientes.', enableBackups: 'Activar respaldos programados', frequency: 'Frecuencia', daily: 'Diario', weekly: 'Semanal', stats: 'Estadísticas de organización', rules: 'Reglas de guardado automático', rulesCopy: 'Guarda pestañas de dominios coincidentes en una sesión elegida.', addRule: 'Agregar regla', privacy: 'Privacidad', privacyCopy: 'Save Tabs guarda títulos, URLs, etiquetas, notas, reglas y preferencias en el almacenamiento del navegador. La sincronización es opcional.', privacyLink: 'Leer política de privacidad', noRules: 'Aún no hay reglas.', enabled: 'Activa', disabled: 'Desactivada', edit: 'Editar', delete: 'Eliminar', deletedSession: 'Sesión eliminada', editRule: 'Editar regla', domains: 'Dominios', saveInto: 'Guardar en', cancel: 'Cancelar', saveRule: 'Guardar regla', backupsOff: 'Los respaldos programados están desactivados.', backupStatus: '{count} respaldos guardados · último: {date}', sessions: 'Sesiones', tabs: 'Pestañas guardadas', favorites: 'Favoritas', tagged: 'Con etiquetas' } };
let sessions = []; let rules = []; let settings = {}; let backups = []; let editingId = null;
const $ = id => document.querySelector(`#${id}`); const t = key => TEXT[settings.language || 'es'][key];
function translate() { const ids = { eyebrow: 'settings', 'preferences-title': 'preferences', 'language-label': 'language', 'theme-label': 'theme', 'sync-label': 'sync', 'shortcuts-title': 'shortcuts', 'shortcuts-copy': 'shortcutsCopy', 'open-shortcuts': 'customize', 'backups-title': 'backups', 'backups-copy': 'backupsCopy', 'backup-enabled-label': 'enableBackups', 'backup-frequency-label': 'frequency', 'stats-title': 'stats', 'rules-title': 'rules', 'rules-copy': 'rulesCopy', 'add-rule': 'addRule', 'privacy-title': 'privacy', 'privacy-copy': 'privacyCopy', 'privacy-link': 'privacyLink', 'domains-label': 'domains', 'save-into-label': 'saveInto', 'cancel-rule': 'cancel', 'save-rule': 'saveRule' }; Object.entries(ids).forEach(([id, key]) => { $(id).textContent = t(key); }); $('backup-frequency').options[0].text = t('daily'); $('backup-frequency').options[1].text = t('weekly'); document.documentElement.lang = settings.language || 'es'; }
async function persistSettings() { await api.storage.local.set({ [KEYS.settings]: settings }); }
async function load() { const data = await api.storage.local.get(Object.values(KEYS)); sessions = Array.isArray(data[KEYS.sessions]) ? data[KEYS.sessions] : []; rules = Array.isArray(data[KEYS.rules]) ? data[KEYS.rules] : []; backups = Array.isArray(data[KEYS.backups]) ? data[KEYS.backups] : []; settings = { language: 'es', theme: 'light', backupFrequency: 'weekly', backupEnabled: false, ...(data[KEYS.settings] || {}) }; $('language').value = settings.language; $('theme').value = settings.theme; $('sync').checked = Boolean(settings.syncEnabled); $('backup-enabled').checked = Boolean(settings.backupEnabled); $('backup-frequency').value = settings.backupFrequency; document.documentElement.dataset.theme = settings.theme; translate(); renderRules(); renderStats(); renderBackupStatus(); }
async function saveRules() { await api.storage.local.set({ [KEYS.rules]: rules }); }
function renderRules() { $('rules').replaceChildren(); if (!rules.length) { $('rules').textContent = t('noRules'); return; } rules.forEach(rule => { const row = document.createElement('div'); row.className = 'rule'; const text = document.createElement('div'); const session = sessions.find(item => item.id === rule.sessionId); const domains = document.createElement('strong'); domains.textContent = rule.domains.join(', '); const sessionName = document.createElement('small'); sessionName.textContent = session?.name || t('deletedSession'); text.append(domains, document.createElement('br'), sessionName); const actions = document.createElement('div'); [['enabled', () => { rule.enabled = !rule.enabled; saveRules().then(renderRules); }], ['edit', () => openRule(rule)], ['delete', () => { rules = rules.filter(item => item.id !== rule.id); saveRules().then(renderRules); }]].forEach(([key, action]) => { const button = document.createElement('button'); button.textContent = key === 'enabled' ? t(rule.enabled ? 'enabled' : 'disabled') : t(key); button.onclick = action; if (key === 'delete') button.className = 'danger'; actions.append(button); }); row.append(text, actions); $('rules').append(row); }); }
function renderStats() { const tabs = sessions.flatMap(session => session.tabs || []); const items = [[t('sessions'), sessions.length], [t('tabs'), tabs.length], [t('favorites'), tabs.filter(tab => tab.pinned).length], [t('tagged'), tabs.filter(tab => tab.tags?.length).length]]; $('stats').replaceChildren(...items.map(([label, value]) => { const item = document.createElement('div'); const number = document.createElement('strong'); number.textContent = value; const text = document.createElement('span'); text.textContent = label; item.append(number, text); return item; })); }
function renderBackupStatus() { $('backup-status').textContent = settings.backupEnabled ? t('backupStatus').replace('{count}', backups.length).replace('{date}', backups[0] ? new Intl.DateTimeFormat(settings.language, { dateStyle: 'short', timeStyle: 'short' }).format(backups[0].at) : '—') : t('backupsOff'); }
function openRule(rule) { editingId = rule?.id || null; $('rule-title').textContent = rule ? t('editRule') : t('addRule'); $('rule-domains').value = rule?.domains.join(', ') || ''; $('rule-session').replaceChildren(...sessions.map(session => new Option(session.name, session.id, false, session.id === rule?.sessionId))); $('rule-dialog').showModal(); }
$('add-rule').onclick = () => openRule(); $('cancel-rule').onclick = () => $('rule-dialog').close();
$('rule-dialog').addEventListener('close', async () => { if ($('rule-dialog').returnValue !== 'save') return; const domains = $('rule-domains').value.split(',').map(value => value.trim()).filter(Boolean); if (!domains.length) return; const rule = { id: editingId || crypto.randomUUID(), sessionId: $('rule-session').value, enabled: true, domains }; const index = rules.findIndex(item => item.id === editingId); index < 0 ? rules.push(rule) : rules[index] = { ...rules[index], ...rule, enabled: rules[index].enabled }; await saveRules(); renderRules(); });
$('language').onchange = async event => { settings.language = event.target.value; await persistSettings(); translate(); renderRules(); renderStats(); renderBackupStatus(); }; $('theme').onchange = async event => { settings.theme = event.target.value; document.documentElement.dataset.theme = settings.theme; await persistSettings(); }; $('sync').onchange = async event => { settings.syncEnabled = event.target.checked; await persistSettings(); if (event.target.checked) await api.storage.sync.set({ [KEYS.sessions]: sessions }); };
async function updateAlarm() { settings.backupEnabled = $('backup-enabled').checked; settings.backupFrequency = $('backup-frequency').value; await persistSettings(); if (!settings.backupEnabled) return api.alarms.clear(ALARM); return api.alarms.create(ALARM, { periodInMinutes: settings.backupFrequency === 'daily' ? 1440 : 10080 }); }
$('backup-enabled').onchange = async () => { await updateAlarm(); renderBackupStatus(); }; $('backup-frequency').onchange = updateAlarm; $('open-shortcuts').onclick = () => api.tabs.create({ url: 'chrome://extensions/shortcuts' }).catch(() => api.runtime.openOptionsPage()); load();
